/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import java.sql.*;
import Connections.ConnectionToDB;
import Forms.Login;
import Voter.AddVoter;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author Lenovo
 */
public class AdminPanel extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form AdminPanel1
     */
    public AdminPanel() {
        initComponents();
        conn = ConnectionToDB.ConnectToDB();
    }
    public void close(){
        WindowEvent we = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(we);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addVoterBn = new javax.swing.JButton();
        addCandidateBn = new javax.swing.JButton();
        addAdminBn = new javax.swing.JButton();
        resultBn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Admin Home");

        addVoterBn.setText("Add Voter");
        addVoterBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVoterBnActionPerformed(evt);
            }
        });

        addCandidateBn.setText("Add Candidate");
        addCandidateBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCandidateBnActionPerformed(evt);
            }
        });

        addAdminBn.setText("Add Admin");
        addAdminBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdminBnActionPerformed(evt);
            }
        });

        resultBn.setText("Result");
        resultBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultBnActionPerformed(evt);
            }
        });

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addAdminBn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addVoterBn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addCandidateBn, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                            .addComponent(resultBn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(addVoterBn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCandidateBn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addAdminBn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultBn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addVoterBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVoterBnActionPerformed
        // TODO add your handling code here:
        new AddVoter().setVisible(true);
    }//GEN-LAST:event_addVoterBnActionPerformed

    private void addCandidateBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCandidateBnActionPerformed
        // TODO add your handling code here:
        new AddCandidatesPanel().setVisible(true);
    }//GEN-LAST:event_addCandidateBnActionPerformed

    private void addAdminBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdminBnActionPerformed
        // TODO add your handling code here:
        new AddUser().setVisible(true);
    }//GEN-LAST:event_addAdminBnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void resultBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultBnActionPerformed
        // TODO add your handling code here:
       try (
             Statement ps = conn.createStatement();
             ResultSet rs = ps.executeQuery("SELECT v.Position, c.First_name, c.Last_name, MAX(v.Votes_count) AS MaxVotes "
                                             + "FROM ( "
                                             + "  SELECT Votes.C_ID, Candidate.First_name, Candidate.Last_name, Candidate.Position, COUNT(*) AS Votes_count "
                                             + "  FROM Votes "
                                             + "  JOIN Candidate ON Votes.C_ID = Candidate.C_ID "
                                             + "  GROUP BY Votes.C_ID, Candidate.First_name, Candidate.Last_name, Candidate.Position "
                                             + ") v "
                                             + "JOIN Candidate c ON c.C_ID = v.C_ID AND c.Position = v.Position "
                                             + "GROUP BY v.Position, c.First_name, c.Last_name")) {
//           System.out.println("Position");           
//           System.out.println(rs.getString("First_name"));

           // Initialize the ViewReport window
            ViewReport vw = new ViewReport();
            
            while (rs.next()) {
                String position = rs.getString("Position");
                String firstName = rs.getString("First_name");
                String lastName = rs.getString("Last_name");
                int maxVotes = rs.getInt("MaxVotes");
                System.out.printf("%s: %s %s (%d votes)%n", position, firstName, lastName, maxVotes);
//                System.out.println("Check");
                
                switch (position.trim()) {// has white space, fuuuk!
                case "President":
                    ViewReport.presidentLb.setText(firstName+ " "+ lastName + " (" + maxVotes + " votes)");
                    System.out.println("Check");
                    break;
                case "Secretary":
                    ViewReport.secretaryLb.setText(firstName+ " "+ lastName + " (" + maxVotes + " votes)");
                    System.out.println("Check");
                    break;
                case "Auditor":
                    ViewReport.auditorLb.setText(firstName+ " "+ lastName + " (" + maxVotes + " votes)");
                    System.out.println("Check");
                    break;
                case "Treasurer":
                    ViewReport.treasurerLb.setText(firstName+ " "+ lastName + " (" + maxVotes + " votes)");
                    System.out.println("Check");
                    break;
                default:
                    System.err.printf("Unknown position: %s%n", position);
                    break;
            }
                
                vw.setVisible(true);
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

    
      
    }//GEN-LAST:event_resultBnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAdminBn;
    private javax.swing.JButton addCandidateBn;
    private javax.swing.JButton addVoterBn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton resultBn;
    // End of variables declaration//GEN-END:variables
}
